services:
    web:
        build:
            context: ./
            target: dev
        volumes:
            - .:/src
        command: node index.js
        ports: 
            - "5000:5000"
        environment:
            NODE_ENV: development